### PR TITLE
master-qa-15320

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-15320

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:retest

**Comment by vicnate5** [comment]
ci:retest

**Comment by jaredzimmerman1** [comment]
No test changes needed :)

**Comment by jaredzimmerman1** [comment]
Pushed to BChiu.
- ee-6.2.10 - https://github.com/brianchiu/liferay-portal-ee/pull/3777
- ee-6.2.x - https://github.com/brianchiu/liferay-portal-ee/pull/3776
- master - https://github.com/brianchiu/liferay-portal/pull/203

**Pull request closed without merging**
