### PR TITLE
master-qa-14851

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-14851

### CODE REVIEW

**Comment by jaredzimmerman1** [comment]
Pushed back to VWare.
- Remove duplicate CalendarConfiguration#USER_SETTINGS_TIME_FORMAT_SELECT locator.

**Comment by vicnate5** [comment]
Rebased branch.

**Comment by jaredzimmerman1** [comment]
SF for VWare.
- Renamed Calendar#viewWeekStartMonth to Calendar#viewWeekStartDayViaMonthView.
- Renamed Calendar#viewWeekStartSmallCalendar to Calendar#viewWeekStartDayViaSmallCalendar.
- Renamed Calendar#viewWeekStartWeek to Calendar#viewWeekStartDayViaWeekView.

**Comment by jaredzimmerman1** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/123

**Comment by jaredzimmerman1** [comment]
Pushed to BChiu.
- ee-6.2.10 - https://github.com/brianchiu/liferay-portal-ee/pull/3694
- ee-6.2.x - https://github.com/brianchiu/liferay-portal-ee/pull/3693
- master - https://github.com/brianchiu/liferay-portal/pull/123

**Pull request closed without merging**
