### PR TITLE
master-qa-15109

### PR DESCRIPTION
**Pull request by vicnate5**
https://issues.liferay.com/browse/LRQA-15109

### CODE REVIEW

**Comment by vicnate5** [comment]
Will Fix

**Comment by vicnate5** [comment]
Nevermind. Failure is due to macro changes missing. This will build successfully in full PR

**Comment by jaredzimmerman1** [comment]
Pushed paths back to VWare.
- Remove blank row from top of RSS path file.
- Add CURRENT_SITE_CALENDARS locators back to PGCalendar.path.

**Comment by vicnate5** [comment]
Needs to be rebased. Will send a new PR.

**Pull request closed without merging**
